### ISSUE TITLE
As a developer, I can specify the rate at which automated blue/green rollouts proceed

### ISSUE THREAD

**Issue by rickrain** [Microsoft/entref-spring-boot#138]
_Copied from Azure Dev Ops Backlog_

**Comment by day-jeff** [comment]
Here is an article describing an approach to implementing this functionality: https://azure.microsoft.com/en-gb/blog/blue-green-deployments-using-azure-traffic-manager/

**Comment by day-jeff** [comment]
moved to entref-appservice-containers project
