### ISSUE TITLE
Script imports sample foods data downloaded from Department of Agriculture

### ISSUE THREAD

**Issue by rickrain** [Microsoft/entref-spring-boot#139]
_Copied from Azure Dev Ops Backlog_

Use import script to get sample data from the following location to populate CosmosDB. This will be accessed using SQL like queries from DocumentDB. 

https://data.nal.usda.gov/dataset/usda-branded-food-products-database

Tasks:
- Import data to CosmosDB collection with SQL API
- Convert default column names to camelCase (dashes must be removed)
  - Spring Boot auto linking doesn't support dashes
  - _"This may not be relevant currently based on the current sprint. This was for when the scripts needed to be changed for DocDB uploading which hasn't been rescoped since that previous PR before the break for winter holidays."_
- Convert ingredients list to JSON array
  - Answer: "There is no explicit need to put it in an array--it's simply a JSON best-practice. Totally ok to break this out into a separate user-story that we prioritize low."
  - Question: "I currently have extracted it as a string with commas within it. Separating it out would be it's own thing most likely. Is this for a filterable search or something else in particular?"

**Comment by rickrain** [comment]
This makes no sense based on the current project / repo.  Probably an earlier thought/vision.  Suggest closing.

**Comment by day-jeff** [comment]
Agree. This was a proposal I made related to switching from music data to food data in order to implement a one user/one shopping domain model, which is common in many real-world scenarios. While the intent/goal is still valid, it is simpler to continue using the existing IMDB data and implementing playlist functionality.
